# Copyright 2023 Vipshop Inc. All Rights Reserved.
# Author: Weida Lei (edward.lei@vipshop.com)
#
cc_binary(
    name = "main",
    srcs = [
        "main.cc",
    ],
    copts = [
        "-std=c++17",
    ],
)
